#============================== Configuration Apache TomCat
server:
  port: 5000
#============================== Configuration Logging
logging:
  file: /tmp/log/user-service.log
  level:
    root: INFO
    org.springframework: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
    com.trl.userservice: DEBUG

spring:
  profiles.active: dev
  application:
    name: user-service

  #============================== Configuration Oracle DB
  datasource:
    username: USR_MS
    password: 6.EU2:onSlpo
    url: jdbc:oracle:thin:@35.180.156.70:1521:libprod
    driver-class-name: oracle.jdbc.OracleDriver

  #============================== Configuration JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false