#============================== Configuration Apache TomCat
server:
  port: 8081
#============================== Configuration Logging
logging:
  file: /tmp/log/user-service.log
  level:
    root: INFO
    org.springframework: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
    com.trl.userservice: DEBUG

spring:
  profiles.active: dev
  application:
    name: user-service

  #============================== Configuration PostgreSQL
  datasource:
    username: developer
    password: Nqa2GrwJ5dqu
    url: jdbc:postgresql://ec2-15-188-76-238.eu-west-3.compute.amazonaws.com/user_service
    driver-class-name: org.postgresql.Driver

  #============================== Configuration JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create